### ISSUE TITLE
Original images

### ISSUE THREAD

**Issue by SCoulY** [microsoft/CanadianBuildingFootprints#5]
Hi, i see your newly built up building datasets but only the footprints (the label) can be downloaded from your link in README. Can we get the original training images as well?

**Comment by TimuSumisu** [comment]
The imagery utilized is Bing Maps aerial imagery. You can check out access details here: https://docs.microsoft.com/en-us/bingmaps/rest-services/imagery/

**Comment by SCoulY** [comment]
Many thanks!

**Comment by tumbleintoyourheart** [comment]
Hi,
I'm new to geojson and do not know how to download images/ label masks from given geojson files. Can you give me some resources on how to do this? Thanks.

**Comment by SCoulY** [comment]
> Hi,
> I'm new to geojson and do not know how to download images/ label masks from given geojson files. Can you give me some resources on how to do this? Thanks.

Label masks are encoded in geojson (just another format which can be translated to label mask by code and u can check it on README page) 
For imagery, they are held in the above microsoft api.

**Comment by tumbleintoyourheart** [comment]
> > Hi,
> > I'm new to geojson and do not know how to download images/ label masks from given geojson files. Can you give me some resources on how to do this? Thanks.
> 
> Label masks are encoded in geojson (just another format which can be translated to label mask by code and u can check it on README page)
> For imagery, they are held in the above microsoft api.

Hi @SCoulY. Does the bingmaps api require the given geojson files, or how can we provide it the needed informations to locate those provinces/territories?

**Comment by SCoulY** [comment]
> > > Hi,
> > > I'm new to geojson and do not know how to download images/ label masks from given geojson files. Can you give me some resources on how to do this? Thanks.
> > 
> > 
> > Label masks are encoded in geojson (just another format which can be translated to label mask by code and u can check it on README page)
> > For imagery, they are held in the above microsoft api.
> 
> Hi @SCoulY. Does the bingmaps api require the given geojson files, or how can we provide it the needed informations to locate those provinces/territories?

The geojson only provide label information and I believe they should have an uniform bingmap api to locate the imagery. e.g. /bigemap/imagery/somewhere 
just saying, check it out in their documents and README.
